# Generated by Django 4.2.17 on 2024-12-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cart_dish_order_restaurant_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='dish',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dish_photos/'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
